name: manylinux2010
on: [push, pull_request]
jobs:
  manylinux2010_x86_64:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2010_x86_64
    strategy:
      matrix:
        python-abi: [cp36-cp36m, cp37-cp37m, cp38-cp38, cp39-cp39]
    steps:
      - uses: actions/checkout@v1
      - name: Install build dependencies
        run: |
          /opt/python/${{ matrix.python-abi }}/bin/pip install --upgrade pip setuptools wheel
      - name: Set environment variables
        shell: bash
        run: |
          echo "PKGVER=$(/opt/python/${{ matrix.python-abi }}/bin/python setup.py --version)" >> $GITHUB_ENV
      - name: Build linux_x86_64 wheel
        env:
          PYXMLSEC_STATIC_DEPS: true
          # disable libxml2-2.9.12 because of https://gitlab.gnome.org/GNOME/libxslt/-/issues/52
          PYXMLSEC_LIBXML2_VERSION: 2.9.10
        run: |
          /opt/python/${{ matrix.python-abi }}/bin/python setup.py bdist_wheel
      - name: Label manylinux2010_x86_64 wheel
        run: |
          ls -la dist/
          auditwheel show dist/xmlsec-${{ env.PKGVER }}-${{ matrix.python-abi }}-linux_x86_64.whl
          auditwheel repair dist/xmlsec-${{ env.PKGVER }}-${{ matrix.python-abi }}-linux_x86_64.whl
          ls -l wheelhouse/
          auditwheel show wheelhouse/xmlsec-${{ env.PKGVER }}-${{ matrix.python-abi }}-manylinux2010_x86_64.whl
      - name: Install test dependencies
        run: |
          /opt/python/${{ matrix.python-abi }}/bin/pip install --upgrade -r requirements-test.txt
          /opt/python/${{ matrix.python-abi }}/bin/pip install xmlsec --only-binary=xmlsec --no-index --find-links=wheelhouse/
      - name: Run tests
        run: |
          /opt/python/${{ matrix.python-abi }}/bin/pytest -v --color=yes
