name: manylinux2010
on: [push]
jobs:
  manylinux2010_x86_64:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2010_x86_64
    strategy:
      matrix:
        python-abi: [cp27-cp27m, cp27-cp27mu, cp35-cp35m, cp36-cp36m, cp37-cp37m, cp38-cp38]
    steps:
      - uses: actions/checkout@v1
      - name: Install build dependencies
        run: |
          /opt/python/${{ matrix.python-abi }}/bin/pip install --upgrade pip setuptools wheel
      - name: Set environment variables
        shell: bash
        run: |
          echo ::set-env name=PKGVER::$(/opt/python/${{ matrix.python-abi }}/bin/python setup.py --version)
      - name: Build linux_x86_64 wheel
        env:
          STATIC_DEPS: true
        run: |
          /opt/python/${{ matrix.python-abi }}/bin/python setup.py bdist_wheel
      - name: Label manylinux2010_x86_64 wheel
        run: |
          ls -la dist/
          auditwheel show dist/xmlsec-${PKGVER}-${{ matrix.python-abi }}-linux_x86_64.whl
          auditwheel repair dist/xmlsec-${PKGVER}-${{ matrix.python-abi }}-linux_x86_64.whl
          ls -l wheelhouse/
          auditwheel show wheelhouse/xmlsec-${PKGVER}-${{ matrix.python-abi }}-manylinux2010_x86_64.whl
      - name: Install test dependencies
        run: |
          /opt/python/${{ matrix.python-abi }}/bin/pip install --upgrade -r requirements-test.txt
          /opt/python/${{ matrix.python-abi }}/bin/pip install xmlsec --only-binary=xmlsec --no-index --find-links=wheelhouse/
      - name: Run tests
        run: |
          /opt/python/${{ matrix.python-abi }}/bin/pytest -v
      - name: Upload dist
        env:
          TWINE_NON_INTERACTIVE: true
          TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.pypi_token }}
        run: |
          /opt/python/${{ matrix.python-abi }}/bin/pip install twine
          /opt/python/${{ matrix.python-abi }}/bin/twine upload wheelhouse/xmlsec-${PKGVER}-${{ matrix.python-abi }}-manylinux2010_x86_64.whl
